language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
    - jmeter-build-steps
    - create-provider-specific-builders

services:
  - rabbitmq
  - mongodb
  - cassandra

before_install: chmod +x ./config/travis-scripts/*

install:
  - ./config/travis-scripts/prepare-kafka.sh
  - ./config/travis-scripts/prepare-couchbase.sh

notifications:
  # TODO return to normal after testing
  email: false
  #slack: excelian-bigdata:zR1fW9d5eW5C3i0oLrHmoCf5

# cache maven repository to speed up build
cache:
  directories:
    - ~/.gradle
