language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
    - jmeter-build-steps
    - 11-add-couchbase-cache-loader-class-implementation

services:
  - rabbitmq
  - mongodb
  - cassandra

before_install: chmod +x ./config/travis-scripts/*

install:
  - ./config/travis-scripts/prepare-kafka.sh
  - ./config/travis-scripts/prepare-couchbase.sh

notifications:
  # TODO
  email: false
  # TODO slack: excelian-bigdata:zR1fW9d5eW5C3i0oLrHmoCf5
