language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
    - jmeter-build-steps
    - create-provider-specific-builders
    - jmeter-multithreaded-tests
    - 53-alternative-cache-implementations
    - Vertx-REST-Spike

services:
  - rabbitmq
  - mongodb

before_install:
  - chmod +x ./config/travis-scripts/*
  - ./config/travis-scripts/prepare-environment.sh

install:
  - ./config/travis-scripts/prepare-kafka.sh
  - ./config/travis-scripts/prepare-couchbase.sh
  - ./config/travis-scripts/prepare-cassandra.sh

notifications:
  slack: exceliandev:1eNY8ozgMfUYwzAECmL4LNHi

# cache maven repository to speed up build
cache:
  directories:
    - ~/.gradle
    - ~/binaries

script: |
  gradle check &&
  ./config/travis-scripts/run-rest-test.sh &&
  gradle :mache-example:putClient -Parg=10,Cassandra,localhost &&
  gradle :mache-example:putClient -Parg=10,Mongo,localhost &&
  gradle :mache-example:putClient -Parg=10,Couchbase,localhost

addons:
  apt:
    sources:
      - mono-beta
    packages:
      - mono-devel
      - nunit-console