language: java
jdk:
  - oraclejdk8

services:
  - rabbitmq
  - mongodb

before_install:
  - chmod +x ./config/travis-scripts/*
  - chmod +x gradlew
  - ./config/travis-scripts/prepare-environment.sh

install:
  - ./config/travis-scripts/prepare-kafka.sh
  - ./config/travis-scripts/prepare-couchbase.sh
  - ./config/travis-scripts/prepare-cassandra.sh

notifications:
  slack: exceliandev:1eNY8ozgMfUYwzAECmL4LNHi

# cache maven repository to speed up build
cache:
  directories:
    - ~/.gradle
    - ~/binaries

script: |
  ./gradlew check &&
  ./config/travis-scripts/run-rest-test.sh &&
  ps aux && ps aux | grep cassandra && tail -n 500 nohup.out &&
  ./gradlew :mache-example:putClient -Parg=10,Cassandra,localhost &&
  ./gradlew :mache-example:putClient -Parg=10,Mongo,localhost &&
  ./gradlew :mache-example:putClient -Parg=10,Couchbase,localhost

addons:
  apt:
    sources:
      - mono-beta
    packages:
      - mono-devel
      - nunit-console