language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
    - travis-further-integration
services:
  - rabbitmq
  - mongodb
  - cassandra

install:
  ## Install and start kafka
  - curl http://mirrors.ibiblio.org/apache/kafka/0.8.1.1/kafka_2.9.2-0.8.1.1.tgz > kafka.tgz
  - tar -xzf kafka.tgz
  - cd kafka_2.9.2-0.8.1.1
  - ./bin/zookeeper-server-start.sh config/zookeeper.properties &
  - sleep 3
  - ./bin/kafka-server-start.sh config/server.properties &
  - sleep 5
  - ./bin/kafka-topics.sh --zookeeper localhost:2181 --topic foobar --partition 1 --replication-factor 1 --create
  - cd ../

