language: java
sudo: required
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
    - jmeter-build-steps
    - create-provider-specific-builders
    - jmeter-multithreaded-tests
    - travis-mono-eval
    - couchprovcleanup

services:
  - rabbitmq
  - mongodb
  - cassandra

before_install:
 - chmod +x ./config/travis-scripts/*
 - ./config/travis-scripts/prepare-mono.sh

install:
  - ./config/travis-scripts/compile-test-mono.sh
  - ./config/travis-scripts/prepare-kafka.sh
  - ./config/travis-scripts/prepare-couchbase.sh


notifications:
  slack: exceliandev:1eNY8ozgMfUYwzAECmL4LNHi

# cache maven repository to speed up build
cache:
  directories:
    - ~/.gradle
    - ~/binaries

script:
  - gradle check
  - gradle :mache-example:putClient -Parg=10,Cassandra,localhost
  - gradle :mache-example:putClient -Parg=10,Mongo,localhost
  - gradle :mache-example:putClient -Parg=10,Couchbase,localhost

